version: '3.5'

services:
  frontend-angular-services:
    container_name: frontend-gipherapp-final3
    build: ./
    volumes:
      - './:/usr/src/app'
    ports:
      - "4204:4200"
    command: >
      bash -c "npm start"

  docker-nginx:
    container_name: frontend-docker-nginx1
    build: ./
    ports:
      - "81:80"
    command: ["nginx", "-g", "daemon off;"]
    links:
      - frontend-angular-services